# config/agents.yaml
ppo_config:
  num_players: 6
  learning_rate: 3e-4
  weight_decay: 1e-5
  buffer_size: 50000
  batch_size: 512
  gamma: 0.99
  clip_epsilon: 0.2
  value_coeff: 0.5
  entropy_coeff: 0.01
  max_grad_norm: 0.5
  episodes_per_update: 50
  max_updates: 1000
  save_dir: "checkpoints"
  save_interval: 200
  log_interval: 10
  input_dim: 128

training_env:
  big_blind: 20
  initial_stack: 1000
  max_raise_multiplier: 2.0

model_params:
  hidden_dim: 256
  num_layers: 3
  dropout: 0.1